version: "3"
services:
   db:
     image: orientdb:2.2.37
     environment:
     - "ORIENTDB_ROOT_PASSWORD=dalongdemo"
     tty: true
     volumes: 
     - "./config:/orientdb/config"
     - "./databases:/orientdb/databases"
     - "./backup:/orientdb/backup"
     - "./db:/db"
     ports: 
     - "2424:2424"
     - "2480:2480"